### PR TITLE
Add perfectscale to the list of k8s solutions

### PR DESCRIPTION
**Pull request by mikeskali**

### CODE REVIEW

**Comment by apurvabhandari** [comment]
Please add under `Cost Optimisation` tab

**Comment by mikeskali** [comment]
> Please add under `Cost Optimisation` tab

@apurvabhandari while our offering includes cost optimization, our emphasize is on running k8s at scale. Big part of current and future offer deals with resilience more than cost. Therefore, continuous optimization is more suitable. This is also the CNCF category we are part off. WDYT? Does it make sense?

**Comment by mikeskali** [comment]
> Please add under `Cost Optimisation` tab

@apurvabhandari moved to Cost Optimisation section. Hope it is ok now.

**Comment by apurvabhandari** [comment]
Thank you and Thanks for raising PR!

**Pull request merged**
